blueprint:
  name: Zone Entering Notification
  description: Send a notification to a device when a person enters a specific zone.
  domain: automation
  source_url: https://github.com/Berloedie1985/blueprint/blob/main/entering_zone.yaml
  author: Arickx Pieter
  input:
    person_entity:
      name: Person
      selector:
        entity:
          filter:
            domain: person
    zone_entity:
      name: Zone
      selector:
        entity:
          filter:
            domain: zone
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          filter:
            integration: mobile_app

triggers:
  trigger: state
  entity_id: !input person_entity

variables:
  zone_entity: !input zone_entity
  # This is the state of the person when it's in this zone.
  zone_state: "{{ states[zone_entity].name }}"
  person_entity: !input person_entity
  person_name: "{{ states[person_entity].name }}"

conditions:
  condition: template
  value_template: "{{ (zone_entity == 'zone.home' and trigger.from_state.state != 'home' and trigger.to_state.state == 'home') or (trigger.from_state.state != zone_state and trigger.to_state.state == zone_state) }}"

actions:
  - alias: "Notify that a person has entered the zone"
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    message: "{{ person_name }} has entered {{ zone_state }}"